#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check linting errors
npm run check-lint-ui || 
{
    echo "Eslint check failed."
    false;
}

# Check types
npm run check-types || 
{
    echo "Failed type checking."
    false;
}


echo "All tests passed. Ready to commit!!" 
